name: Run Shell Commnds
on: [push]

jobs:
  runs-shell-command:
    run-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo "Hello Sec Guru - First Github action file yml file"
